import Navebar from "./components/Navebar"
import Footer from "./components/Footer"
import './globals.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navebar />
        {children}
        <Footer />
        </body>
    </html>
  )
}
